<<<<<<< HEAD
english = {
name: "English",
introText: "Sorting Based on Educational Technology",
introSubText: "Design and Play Sorting Games",
homeButton: "Home",
examples: "Online Examples",
help:"Resources",
information: "About SorBET",
manual: "Manual",
publicationsDropdown:"Publications",
about:"About",
manualUrl:"http://etl.ppp.uoa.gr/sorbet/manuals/manual-eng.pdf",
designG: "Design a Game",
loadG: "Load Game",
play: "Play",
download: "Download",
objects_Name: "Objects",
tableField: "Field",
edit: "Edit",
count: "Score",
start: "Start",
stop: "Stop",
gameOver: "The game has finished",
scoreModal: "Classification Table",
playAnswersTable: "Objects you classified",
deleteIco: "Delete object (row)",
addPoint: "Add object (row)",
deleteField: "Delete selected category (column)",
addAttribute: "Add Category (column)",
close: "Close",
downloadScore: "Download Score",
category: "Category",
classifObj: "Objects you classified",
classUncl: "Unclassified",
show: "Show Score and Statistics",
classtable: "Classification Table",
correct:"Correct",
outof:" out of ",
text:"text",
image:"image",
shape:"shape",
circle:"circle",
rectangle:"rectangle",
field1:"Field1",
field2:"Field2",
sometext:"sometext",
classesofAnimalsText: "Classes of Animals",
seasonalDietText:"Seasonal Diet",
theNumbersText:"The Numbers",
fallingAnglesText:"Falling Angles",
theAppGameText:"The App Game",
biodegradableMaterialText:"Biodegradable Material",
howLongForDegradationText:"How long for Degradation?",
multiCultiText:"Multi Culti Game",
ancientGreekSyntaxText:"Ancient Greek Syntax",
ancientparentheticText:"Ancient Parenthetic",
historyText:"History",
latinText:"Latin",
philoshophyText:"Philosophy",
ancientGreekNounsText:"Ancient Greek Nouns",
AncientGreekAnimalsText:"Ancient Greek Animals",
messageSave:"Please enter a name for the game:",
name:"name",
deletemsg:"Please select a category (column) to delete by clicking on its checkbox"

}

greek = {
  name: "Greek",
  introText: "Sorting Based on Educational Technology",
  introSubText: "Σχεδιάστε και παίξτε Παιχνίδια Ταξινόμησης",
  homeButton: "Αρχική",
  examples: "Έτοιμα Παραδείγματα",
  help: "Υποστηρικτικό Υλικό",
  information: "Σχετικά με το SorBET",
  manual: "Εγχειρίδιο Χρήσης",
  publicationsDropdown:"Δημοσιεύσεις",
  about:"Σχετικά",
  manualUrl: "http://etl.ppp.uoa.gr/sorbet/manuals/manual-gr.pdf",
  designG: "Σχεδίασε ένα παιχνίδι",
  loadG: "Φόρτωση παιχνιδιού",
  play: "Παίξε",
  download: "Λήψη",
  objects_Name: "Αντικείμενα",
  tableField: "Πεδίο",
  edit: "Επεξεργασία",
  count: "Σκορ",
  start: "Εκκίνηση",
  stop: "Τέλος",
  gameOver: "Το παιχνίδι τελείωσε",
  scoreModal: "Πίνακας Ταξινόμησης",
  playAnswersTable: "Αντικείμενα που ταξινόμησες",
  deleteIco: "Διαγραφή Αντικειμένου",
  addPoint: "Προσθήκη Αντικειμένου",
  delCat: "Διαγραφή επιλεγμένης κατηγορίας",
  addAttribute: "Προσθήκη Κατηγορίας",
  close: "Κλείσιμο",
  downloadScore: "Λήψη Σκορ",
  category: "Κατηγορία: ",
  classifObj: " Αντικείμενα που ταξινομήθηκαν",
  classUncl: "Αταξινόμητα",
  show: "Εμφάνιση Σκορ και Στατιστικών",
  classtable: "Πίνακας Ταξινόμησης",
  correct:"Σωστά ",
  outof:" από ",
  text:"κείμενο",
  image:"εικόνα",
  shape:"σχήμα",
  circle:"κύκλος",
  rectangle:"ορθογώνιο",
  field1:"Πεδίο1",
  field2:"Πεδίο2",
  sometext:"γράψε κείμενο",
  classesofAnimalsText: "Ταξινομίες Ζώων",
  seasonalDietText:"Εποχική Διατροφή",
  theNumbersText:"Οι Αριθμοί",
  fallingAnglesText:"Γωνίες",
  theAppGameText:"Το Παιχνίδι των Εφαρμογών",
  biodegradableMaterialText:"Βιοδιασπώμενα Υλικά",
  howLongForDegradationText:"Πόσο καιρό θέλει για να διασπασθεί;",
  multiCultiText:"Κόσμος",
  ancientGreekSyntaxText:"Αρχαιοελληνικό Συντακτικό",
  ancientparentheticText:"Αρχαία Παραθετικά",
  historyText:"Ιστορικά Γεγονότα",
  latinText:"Συζυγίες της Λατινικής Γλώσσας",
  philoshophyText:"Έλληνες Φιλόσοφοι",
  ancientGreekNounsText:"Αρχαία Ελληνικά Ουσιαστικά",
  AncientGreekAnimalsText:"Αρχαία Ελληνικά Ζώα",
  messageSave:"Παρακαλώ εισάγετε ένα όνομα για το παιχνίδι:",
  name:"Όνομα",
  deletemsg:"Παρακαλώ επιλέξτε μια κατηγορία (column) να διαγράψετε πατώντας το πλαίσιο ελέγχου της"

}
=======
english = {
name: "English",
introText: "Sorting Based on Educational Technology",
introSubText: "Design and Play Sorting Games",
homeButton: "Home",
examples: "Online Examples",
help:"Resources",
information: "About SorBET",
manual: "Manual",
publicationsDropdown:"Publications",
about:"About",
manualUrl:"http://etl.ppp.uoa.gr/sorbet/manuals/manual-eng.pdf",
designG: "Design a Game",
loadG: "Load Game",
play: "Play",
download: "Download",
objects_Name: "Objects",
tableField: "Field",
edit: "Edit",
count: "Score",
start: "Start",
stop: "Stop",
gameOver: "The game has finished",
scoreModal: "Classification Table",
playAnswersTable: "Objects you classified",
deleteIco: "Delete object (row)",
addPoint: "Add object (row)",
deleteField: "Delete selected category (column)",
addAttribute: "Add Category (column)",
close: "Close",
downloadScore: "Download Score",
category: "Category",
classifObj: "Objects you classified",
classUncl: "Unclassified",
show: "Show Score and Statistics",
classtable: "Classification Table",
correct:"Correct",
outof:" out of ",
text:"text",
image:"image",
shape:"shape",
circle:"circle",
rectangle:"rectangle",
field1:"Field1",
field2:"Field2",
sometext:"sometext",
classesofAnimalsText: "Classes of Animals",
seasonalDietText:"Seasonal Diet",
theNumbersText:"The Numbers",
fallingAnglesText:"Falling Angles",
theAppGameText:"The App Game",
biodegradableMaterialText:"Biodegradable Material",
howLongForDegradationText:"How long for Degradation?",
multiCultiText:"Multi Culti Game",
ancientGreekSyntaxText:"Ancient Greek Syntax",
ancientparentheticText:"Ancient Parenthetic",
historyText:"History",
latinText:"Latin",
philoshophyText:"Philosophy",
ancientGreekNounsText:"Ancient Greek Nouns",
AncientGreekAnimalsText:"Ancient Greek Animals",
messageSave:"Please enter a name for the game:",
name:"name",
deletemsg:"Please select a category (column) to delete by clicking on its checkbox"

}

greek = {
  name: "Greek",
  introText: "Sorting Based on Educational Technology",
  introSubText: "Σχεδιάστε και παίξτε Παιχνίδια Ταξινόμησης",
  homeButton: "Αρχική",
  examples: "Έτοιμα Παραδείγματα",
  help: "Υποστηρικτικό Υλικό",
  information: "Σχετικά με το SorBET",
  manual: "Εγχειρίδιο Χρήσης",
  publicationsDropdown:"Δημοσιεύσεις",
  about:"Σχετικά",
  manualUrl: "http://etl.ppp.uoa.gr/sorbet/manuals/manual-gr.pdf",
  designG: "Σχεδίασε ένα παιχνίδι",
  loadG: "Φόρτωση παιχνιδιού",
  play: "Παίξε",
  download: "Λήψη",
  objects_Name: "Αντικείμενα",
  tableField: "Πεδίο",
  edit: "Επεξεργασία",
  count: "Σκορ",
  start: "Εκκίνηση",
  stop: "Τέλος",
  gameOver: "Το παιχνίδι τελείωσε",
  scoreModal: "Πίνακας Ταξινόμησης",
  playAnswersTable: "Αντικείμενα που ταξινόμησες",
  deleteIco: "Διαγραφή Αντικειμένου",
  addPoint: "Προσθήκη Αντικειμένου",
  delCat: "Διαγραφή επιλεγμένης κατηγορίας",
  addAttribute: "Προσθήκη Κατηγορίας",
  close: "Κλείσιμο",
  downloadScore: "Λήψη Σκορ",
  category: "Κατηγορία: ",
  classifObj: " Αντικείμενα που ταξινομήθηκαν",
  classUncl: "Αταξινόμητα",
  show: "Εμφάνιση Σκορ και Στατιστικών",
  classtable: "Πίνακας Ταξινόμησης",
  correct:"Σωστά ",
  outof:" από ",
  text:"κείμενο",
  image:"εικόνα",
  shape:"σχήμα",
  circle:"κύκλος",
  rectangle:"ορθογώνιο",
  field1:"Πεδίο1",
  field2:"Πεδίο2",
  sometext:"γράψε κείμενο",
  classesofAnimalsText: "Ταξινομίες Ζώων",
  seasonalDietText:"Εποχική Διατροφή",
  theNumbersText:"Οι Αριθμοί",
  fallingAnglesText:"Γωνίες",
  theAppGameText:"Το Παιχνίδι των Εφαρμογών",
  biodegradableMaterialText:"Βιοδιασπώμενα Υλικά",
  howLongForDegradationText:"Πόσο καιρό θέλει για να διασπασθεί;",
  multiCultiText:"Κόσμος",
  ancientGreekSyntaxText:"Αρχαιοελληνικό Συντακτικό",
  ancientparentheticText:"Αρχαία Παραθετικά",
  historyText:"Ιστορικά Γεγονότα",
  latinText:"Συζυγίες της Λατινικής Γλώσσας",
  philoshophyText:"Έλληνες Φιλόσοφοι",
  ancientGreekNounsText:"Αρχαία Ελληνικά Ουσιαστικά",
  AncientGreekAnimalsText:"Αρχαία Ελληνικά Ζώα",
  messageSave:"Παρακαλώ εισάγετε ένα όνομα για το παιχνίδι:",
  name:"Όνομα",
  deletemsg:"Παρακαλώ επιλέξτε μια κατηγορία (column) να διαγράψετε πατώντας το πλαίσιο ελέγχου της"

}
>>>>>>> 64a3550 (this is to work with the platform)
